groups:
  - id: entity.k8s.cluster
    type: entity
    stability: development
    name: k8s.cluster
    brief: >
      A Kubernetes Cluster.
    attributes:
      - ref: k8s.cluster.name
        role: descriptive
      - ref: k8s.cluster.uid
        role: identifying

  - id: entity.k8s.node
    type: entity
    stability: development
    name: k8s.node
    brief: >
      A Kubernetes Node object.
    attributes:
      - ref: k8s.node.name
        role: descriptive
      - ref: k8s.node.uid
        role: identifying
      - ref: k8s.node.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.node.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.namespace
    type: entity
    stability: development
    name: k8s.namespace
    brief: >
      A Kubernetes Namespace.
    attributes:
      - ref: k8s.namespace.name
        role: identifying
      - ref: k8s.namespace.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.namespace.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.pod
    type: entity
    stability: development
    name: k8s.pod
    brief: >
      A Kubernetes Pod object.
    attributes:
      - ref: k8s.pod.uid
        role: identifying
      - ref: k8s.pod.name
        role: descriptive
      - ref: k8s.pod.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.pod.annotation
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.pod.ip
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.pod.hostname
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.pod.start_time
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.container
    type: entity
    stability: development
    name: k8s.container
    brief: >
      A container in a [PodTemplate](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates).
    attributes:
      - ref: k8s.container.name
        role: identifying
      - ref: k8s.container.restart_count
        role: descriptive
      - ref: k8s.container.status.last_terminated_reason
        role: descriptive

  - id: entity.k8s.replicaset
    type: entity
    stability: development
    name: k8s.replicaset
    brief: >
      A Kubernetes ReplicaSet object.
    attributes:
      - ref: k8s.replicaset.uid
        role: identifying
      - ref: k8s.replicaset.name
        role: descriptive
      - ref: k8s.replicaset.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.replicaset.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.deployment
    type: entity
    stability: development
    name: k8s.deployment
    brief: >
      A Kubernetes Deployment object.
    attributes:
      - ref: k8s.deployment.uid
        role: identifying
      - ref: k8s.deployment.name
        role: descriptive
      - ref: k8s.deployment.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.deployment.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.statefulset
    type: entity
    stability: development
    name: k8s.statefulset
    brief: >
      A Kubernetes StatefulSet object.
    attributes:
      - ref: k8s.statefulset.uid
        role: identifying
      - ref: k8s.statefulset.name
        role: descriptive
      - ref: k8s.statefulset.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.statefulset.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.daemonset
    type: entity
    stability: development
    name: k8s.daemonset
    brief: >
      A Kubernetes DaemonSet object.
    attributes:
      - ref: k8s.daemonset.uid
        role: identifying
      - ref: k8s.daemonset.name
        role: descriptive
      - ref: k8s.daemonset.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.daemonset.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.job
    type: entity
    stability: development
    name: k8s.job
    brief: >
      A Kubernetes Job object.
    attributes:
      - ref: k8s.job.uid
        role: identifying
      - ref: k8s.job.name
        role: descriptive
      - ref: k8s.job.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.job.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.cronjob
    type: entity
    stability: development
    name: k8s.cronjob
    brief: >
      A Kubernetes CronJob object.
    attributes:
      - ref: k8s.cronjob.uid
        role: identifying
      - ref: k8s.cronjob.name
        role: descriptive
      - ref: k8s.cronjob.label
        role: descriptive
        requirement_level: opt_in
      - ref: k8s.cronjob.annotation
        role: descriptive
        requirement_level: opt_in

  - id: entity.k8s.replicationcontroller
    type: entity
    stability: development
    name: k8s.replicationcontroller
    brief: >
      A Kubernetes ReplicationController object.
    attributes:
      - ref: k8s.replicationcontroller.uid
        role: identifying
      - ref: k8s.replicationcontroller.name
        role: descriptive

  - id: entity.k8s.hpa
    type: entity
    stability: development
    name: k8s.hpa
    brief: >
      A Kubernetes HorizontalPodAutoscaler object.
    attributes:
      - ref: k8s.hpa.uid
        role: identifying
      - ref: k8s.hpa.name
        role: descriptive
      - ref: k8s.hpa.scaletargetref.kind
        role: descriptive
        requirement_level: recommended
      - ref: k8s.hpa.scaletargetref.name
        role: descriptive
        requirement_level: recommended
      - ref: k8s.hpa.scaletargetref.api_version
        role: descriptive
        requirement_level: recommended

  - id: entity.k8s.resourcequota
    type: entity
    stability: development
    name: k8s.resourcequota
    brief: >
      A Kubernetes ResourceQuota object.
    attributes:
      - ref: k8s.resourcequota.uid
        role: identifying
      - ref: k8s.resourcequota.name
        role: descriptive
