groups:
  - id: resource.k8s.cluster
    type: resource
    stability: development
    name: k8s.cluster
    brief: >
      A Kubernetes Cluster.
    attributes:
      - ref: k8s.cluster.name
      - ref: k8s.cluster.uid

  - id: resource.k8s.node
    type: resource
    stability: development
    name: k8s.node
    brief: >
      A Kubernetes Node object.
    attributes:
      - ref: k8s.node.name
      - ref: k8s.node.uid

  - id: resource.k8s.namespace
    type: resource
    stability: development
    name: k8s.namespace
    brief: >
      A Kubernetes Namespace.
    attributes:
      - ref: k8s.namespace.name

  - id: resource.k8s.pod
    type: resource
    stability: development
    name: k8s.pod
    brief: >
      A Kubernetes Pod object.
    attributes:
      - ref: k8s.pod.uid
      - ref: k8s.pod.name
      - ref: k8s.pod.label
      - ref: k8s.pod.annotation
        requirement_level: opt_in

  - id: resource.k8s.container
    type: resource
    stability: development
    name: k8s.container
    brief: >
      A container in a [PodTemplate](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates).
    attributes:
      - ref: k8s.container.name
      - ref: k8s.container.restart_count
      - ref: k8s.container.status.last_terminated_reason

  - id: resource.k8s.replicaset
    type: resource
    stability: development
    name: k8s.replicaset
    brief: >
      A Kubernetes ReplicaSet object.
    attributes:
      - ref: k8s.replicaset.uid
      - ref: k8s.replicaset.name

  - id: resource.k8s.deployment
    type: resource
    stability: development
    name: k8s.deployment
    brief: >
      A Kubernetes Deployment object.
    attributes:
      - ref: k8s.deployment.uid
      - ref: k8s.deployment.name

  - id: resource.k8s.statefulset
    type: resource
    stability: development
    name: k8s.statefulset
    brief: >
      A Kubernetes StatefulSet object.
    attributes:
      - ref: k8s.statefulset.uid
      - ref: k8s.statefulset.name

  - id: resource.k8s.daemonset
    type: resource
    stability: development
    name: k8s.daemonset
    brief: >
      A Kubernetes DaemonSet object.
    attributes:
      - ref: k8s.daemonset.uid
      - ref: k8s.daemonset.name

  - id: resource.k8s.job
    type: resource
    stability: development
    name: k8s.job
    brief: >
      A Kubernetes Job object.
    attributes:
      - ref: k8s.job.uid
      - ref: k8s.job.name

  - id: resource.k8s.cronjob
    type: resource
    stability: development
    name: k8s.cronjob
    brief: >
      A Kubernetes CronJob object.
    attributes:
      - ref: k8s.cronjob.uid
      - ref: k8s.cronjob.name

  - id: resource.k8s.replicationcontroller
    type: resource
    stability: development
    name: k8s.replicationcontroller
    brief: >
      A Kubernetes ReplicationController object.
    attributes:
      - ref: k8s.replicationcontroller.uid
      - ref: k8s.replicationcontroller.name

  - id: resource.k8s.hpa
    type: resource
    stability: development
    name: k8s.hpa
    brief: >
      A Kubernetes HorizontalPodAutoscaler object.
    attributes:
      - ref: k8s.hpa.uid
      - ref: k8s.hpa.name

  - id: resource.k8s.resourcequota
    type: resource
    stability: development
    name: k8s.resourcequota
    brief: >
      A Kubernetes ResourceQuota object.
    attributes:
      - ref: k8s.resourcequota.uid
      - ref: k8s.resourcequota.name
